/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as appProfileImport } from './routes/(app)/profile'
import { Route as productsProductsIndexImport } from './routes/(products)/products.index'
import { Route as productsProductsCreateImport } from './routes/(products)/products.create'
import { Route as productsProductsSlugImport } from './routes/(products)/products.$slug'
import { Route as productsProductsSlugEditImport } from './routes/(products)/products.$slug.edit'

// Create/Update Routes

const appIndexRoute = appIndexImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appProfileRoute = appProfileImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const productsProductsIndexRoute = productsProductsIndexImport.update({
  id: '/(products)/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const productsProductsCreateRoute = productsProductsCreateImport.update({
  id: '/(products)/products/create',
  path: '/products/create',
  getParentRoute: () => rootRoute,
} as any)

const productsProductsSlugRoute = productsProductsSlugImport.update({
  id: '/(products)/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRoute,
} as any)

const productsProductsSlugEditRoute = productsProductsSlugEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => productsProductsSlugRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof rootRoute
    }
    '/(products)/products/$slug': {
      id: '/(products)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof productsProductsSlugImport
      parentRoute: typeof rootRoute
    }
    '/(products)/products/create': {
      id: '/(products)/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof productsProductsCreateImport
      parentRoute: typeof rootRoute
    }
    '/(products)/products/': {
      id: '/(products)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof productsProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(products)/products/$slug/edit': {
      id: '/(products)/products/$slug/edit'
      path: '/edit'
      fullPath: '/products/$slug/edit'
      preLoaderRoute: typeof productsProductsSlugEditImport
      parentRoute: typeof productsProductsSlugImport
    }
  }
}

// Create and export the route tree

interface productsProductsSlugRouteChildren {
  productsProductsSlugEditRoute: typeof productsProductsSlugEditRoute
}

const productsProductsSlugRouteChildren: productsProductsSlugRouteChildren = {
  productsProductsSlugEditRoute: productsProductsSlugEditRoute,
}

const productsProductsSlugRouteWithChildren =
  productsProductsSlugRoute._addFileChildren(productsProductsSlugRouteChildren)

export interface FileRoutesByFullPath {
  '/profile': typeof appProfileRoute
  '/': typeof appIndexRoute
  '/products/$slug': typeof productsProductsSlugRouteWithChildren
  '/products/create': typeof productsProductsCreateRoute
  '/products': typeof productsProductsIndexRoute
  '/products/$slug/edit': typeof productsProductsSlugEditRoute
}

export interface FileRoutesByTo {
  '/profile': typeof appProfileRoute
  '/': typeof appIndexRoute
  '/products/$slug': typeof productsProductsSlugRouteWithChildren
  '/products/create': typeof productsProductsCreateRoute
  '/products': typeof productsProductsIndexRoute
  '/products/$slug/edit': typeof productsProductsSlugEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/': typeof appIndexRoute
  '/(products)/products/$slug': typeof productsProductsSlugRouteWithChildren
  '/(products)/products/create': typeof productsProductsCreateRoute
  '/(products)/products/': typeof productsProductsIndexRoute
  '/(products)/products/$slug/edit': typeof productsProductsSlugEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/'
    | '/products/$slug'
    | '/products/create'
    | '/products'
    | '/products/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/'
    | '/products/$slug'
    | '/products/create'
    | '/products'
    | '/products/$slug/edit'
  id:
    | '__root__'
    | '/(app)/profile'
    | '/(app)/'
    | '/(products)/products/$slug'
    | '/(products)/products/create'
    | '/(products)/products/'
    | '/(products)/products/$slug/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
  productsProductsSlugRoute: typeof productsProductsSlugRouteWithChildren
  productsProductsCreateRoute: typeof productsProductsCreateRoute
  productsProductsIndexRoute: typeof productsProductsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
  productsProductsSlugRoute: productsProductsSlugRouteWithChildren,
  productsProductsCreateRoute: productsProductsCreateRoute,
  productsProductsIndexRoute: productsProductsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)/profile",
        "/(app)/",
        "/(products)/products/$slug",
        "/(products)/products/create",
        "/(products)/products/"
      ]
    },
    "/(app)/profile": {
      "filePath": "(app)/profile.tsx"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx"
    },
    "/(products)/products/$slug": {
      "filePath": "(products)/products.$slug.tsx",
      "children": [
        "/(products)/products/$slug/edit"
      ]
    },
    "/(products)/products/create": {
      "filePath": "(products)/products.create.tsx"
    },
    "/(products)/products/": {
      "filePath": "(products)/products.index.tsx"
    },
    "/(products)/products/$slug/edit": {
      "filePath": "(products)/products.$slug.edit.tsx",
      "parent": "/(products)/products/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
